# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AWS-ECR-Variables
  - name: DOCKER_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)

steps:
- task: Docker@2
  displayName: Build docker image
  inputs:
    containerRegistry: 'AWS_ECR'
    repository: 'nodejs_14_image'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
