version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR - INFRA-REPO...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo APP Build started on `date`
      - echo Building the Docker image..
      - docker build -t alpine-infra-image:latest .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_APP_REPO_NAME:$IMAGE_TAG
            # You may also copy the Shell script content for below URL
      - curl https://gitlab.com/prismacloud-public/shift-left/extension/-/raw/master/aws-codepipeline/image_scan.sh
      - pwd
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_APP_REPO_NAME:$IMAGE_TAG
